"""ML Layer Facade — bridges legacy imports to the modular app.ml package.

Preserves 100% backward compatibility for existing callers.
"""
from .ml import (
    CATEGORIES,
    analyze_complaint,
    calculate_priority,
    classify_category,
    explain_category_reasoning,
    format_category_reasoning_response,
    get_metrics,
    metrics,
    predict_categories,
    predict_category,
    predict_multilabel,
    predict_escalation,
    predict_sentiment,
    priority_label,
    priority_tier,
    score_complaint_row,
    score_escalation_risk,
    score_priority,
    score_sentiment,
    score_unscored,
    sla_deadline_for,
    ticket_summary,
    train,
    train_and_save,
)

__all__ = [
    "CATEGORIES",
    "analyze_complaint",
    "calculate_priority",
    "classify_category",
    "explain_category_reasoning",
    "format_category_reasoning_response",
    "get_metrics",
    "metrics",
    "predict_categories",
    "predict_category",
    "predict_multilabel",
    "predict_escalation",
    "predict_sentiment",
    "priority_label",
    "priority_tier",
    "score_complaint_row",
    "score_escalation_risk",
    "score_priority",
    "score_sentiment",
    "score_unscored",
    "sla_deadline_for",
    "ticket_summary",
    "train",
    "train_and_save",
]
